name: První stránka
favicon: null
layout_spectrum: 0.5471093060914427
typography_spectrum: 0.3452605428174138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eb2e5a'
    - '#ffffff'
    - '#f1778e'
    - '#f5a6b3'
    - '#ed4a6d'
  brandStrength: 0.875
  lightness: 0.6202404196374118
  saturation: 0.16812725877389312
  rhythmicContrast: 0.3983636659104377
purpose: []
